[package]
name = "blockchain_rust"
version = "0.1.0"
author = "Deniz Ozturk <dozturk@ncsu.edu>"
edition = "2021"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
path = "src/main.rs" 
name = "blockchain_rust"

[dependencies]
hex = "0.3.2"
crypto_hash = "0.3.3"